### ISSUE TITLE
Incompatible with Doctrine 2.6

### ISSUE THREAD

**Issue by Majkl578** [consistence/consistence-doctrine#10]
Hello,

Doctrine 2.6.0 has been released, please allow its installation.

Thanks.

**Comment by VasekPurchart** [comment]
Hi, I think I had a bad experience with older ORM versions making BC breaks, but I think this has improved so I allowed minor updates in #11, released as [1.3](https://github.com/consistence/consistence-doctrine/releases/tag/1.3).
