### ISSUE TITLE
Incompatible with Doctrine 2.7

### ISSUE THREAD

**Issue by simPod** [consistence/consistence-doctrine#18]
Hi, just copy pasting this https://github.com/consistence/consistence-doctrine/issues/10

> Hello,
>
> Doctrine 2.7.0 has been released, please allow its installation.
>
> Thanks.

🙏

**Comment by VasekPurchart** [comment]
Is there something which prevents installing it? Because since the last time the dependency has been relaxed to allow also minor versions.

**Comment by simPod** [comment]
Umm, my bad as I though 2.7 is already out (I used `... as 2.7`) and composer complained. I see it's locked on `^2.6.3` so should be good and ready for 2.7. Thanks.
